test:
  image: ibmcom/swift-ubuntu:4.1
  volumes:
      - .:/BluemixAppID
  command: bash -c "cd /BluemixAppID && swift package  --build-path .build-ubuntu clean && swift build  --build-path .build-ubuntu && swift test  --build-path .build-ubuntu"
